/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CalcContainer {
    }
}
declare global {
    interface HTMLCalcContainerElement extends Components.CalcContainer, HTMLStencilElement {
    }
    var HTMLCalcContainerElement: {
        prototype: HTMLCalcContainerElement;
        new (): HTMLCalcContainerElement;
    };
    interface HTMLElementTagNameMap {
        "calc-container": HTMLCalcContainerElement;
    }
}
declare namespace LocalJSX {
    interface CalcContainer {
    }
    interface IntrinsicElements {
        "calc-container": CalcContainer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "calc-container": LocalJSX.CalcContainer & JSXBase.HTMLAttributes<HTMLCalcContainerElement>;
        }
    }
}
